W-11517065 update archive site link
mulesoft/docs-general pull request #129
Opened 2022-07-29 18:25 UTC by hannanelson

2022-07-29 19:06 UTC, cheungaryk requested changes

2022-07-29 19:06 UTC, cheungaryk commented on modules/ROOT/pages/index.adoc
> +When a product version is no longer supported, including products with end-of-life status, its documentation moves to an http://archive.docs.mulesoft.com/[archive site^].
it should be https

2022-08-05 22:35 UTC, IsaacEldridge approved these changes

2022-08-05 22:38 UTC, cheungaryk commented
The change looks good to me so I agree with Isaac's approval. However, I am modifying the nav grouping in the new archive site and the new archive site is not ready to be public yet (for instance, you can see 2 home icons in https://archive.docs.mulesoft.com/). This work is expected to be done early next week - until then, please do not merge.

2022-08-05 22:48 UTC, cheungaryk approved these changes
Please do not merge it yet, as explained in my previous comment. I can merge once the archive site is ready 😄

2022-08-09 17:14 UTC, merged