W-16431086: Document changes around compilation of connectors with Java 17
mulesoft/docs-general pull request #280
Opened 2024-11-14 13:13 UTC by elrodro83

Ref: https://docs.google.com/document/d/1fGOmV5qkiuqqQZe6iN09z_3gxKVeIHdLOTFnaaISlb0/edit?tab=t.0

2025-01-10 13:41 UTC, marianogonzalez requested changes

2025-01-10 13:41 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +From Mule 4.9.0 and onwards, connectors can be compiled with any Java versions providing it can generate bytecode the proper version.
is this grammar ok? I would rephase as `From Mule 4.9.0 and onwards, any Java SDK project can be compiled for Java 17 language level or lower. Any additional dependencies must also be compiled for a language level equal or lower than 17`

Notice that:

* This now includes modules, not only connectors
* It's not making promisises about supporting Java 21 compilation at day zero, since Hyperforce migration might put that at risk

2025-01-10 13:41 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +For this, the version of `mule-modules-parent` must be upgraded to 1.9.0 of higher, and the `java.release.version` set to the minimal Java version that the connector will require. (See xref:java-vers
> must be upgraded to 1.9.0 of higher, and the `java.release.version` set to the minimal Java version that the connector will require

This is incorrect. Setting the parent pom to 1.9.0 will make the connector's MMV to also be 4.9.0. Therefore, there's no point in lowering the language level as there's no way to run that connector in any other mule version. The parent pom should already be pointing to Java 17 and we shouldn't tell customers how to change that

This documentation should make it clear that using 1.9.0 uplifts the MMV and that the connector will Java java 17 as the only supported Java version (e.g: using `@JavaVersionSupport({JAVA_8, JAVA_11, JAVA_17})` wouldn't make sense, they will have to use `@JavaVersionSupport(JAVA_17)`

2025-01-10 13:41 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +If the `mule-modules-parent` is lower than 1.9.0, bytecode level must be for Java 8 (and all of the third-party dependencies as well), and Java 8 must be used to build the connector. Because of this,
> this, use the Java compiler configuration from the Java SDK parent POM.

Same as before, customers shouldn't tamper with the compiler plugin configuration

2025-01-10 17:46 UTC, elrodro83 commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +In Mule 4.9.0 and later, you can compile any Mule project for Java 17 or lower. You must also compile any additional dependencies for Java 17 or lower.
`You must also compile ` -> `You may compile `

2025-01-10 17:54 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +In Mule 4.9.0 and later, you can compile any Mule project for Java 17 or lower. You must also compile any additional dependencies for Java 17 or lower.
actually, it should be `Additional dependencies must be compiled for Java 17 or lower` since 3pp dependencies are already pre-compiled

2025-01-13 13:55 UTC, marianogonzalez requested changes

2025-01-13 13:55 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +The `mule-modules-parent` should be upgraded to version 1.9.0 or later, which automatically sets the `java.release.version` to Java 17. The connector's minimum Mule version will also be 4.9.0, ensuri
>  which automatically sets the `java.release.version` to Java 17
Don't even mention this. Customer doesn't need to know. Just say that to use Java 17 compiled code, the parent pom needs to be 1.9+

2025-01-13 13:55 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +If the `mule-modules-parent` version is earlier than 1.9.0, the bytecode level for the connector and its additional dependencies must be for Java 8, and the connector must be built using Java 8. Beca
>  bytecode level for the connector and its additional dependencies must be for Java 8, and the connector must be built using Java 8

Redundant. Those are essentially the same thing

2025-01-13 13:55 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +If the `mule-modules-parent` version is earlier than 1.9.0, the bytecode level for the connector and its additional dependencies must be for Java 8, and the connector must be built using Java 8. Beca
> Because of this, use the Java compiler configuration from the Java SDK parent POM instead of modifying it.

Remove

2025-01-13 13:55 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +In Mule 4.9.0 and later, you can compile any Mule project for Java 17 or lower. You must also compile any additional dependencies for Java 17 or lower.
@sathya0 please see above comment

2025-01-15 21:03 UTC, marianogonzalez requested changes

2025-01-15 21:03 UTC, marianogonzalez commented on modules/ROOT/pages/_partials/partner-and-customer-guide.adoc
> +The `mule-modules-parent` should be upgraded to version 1.9.0 or later. The connector's minimum Mule version will also be 4.9.0, ensuring compatibility only with Mule 4.9.0 or later. See xref:java-ve
> The `mule-modules-parent` should be upgraded to version 1.9.0 or later

Only when compiling for Java > 8 (or using 3pp libraries compiled like that) is necessary. If staying in Java 8 is a possiblity, then this is not necessary nor a recommendation.

2025-01-20 17:48 UTC, marianogonzalez submitted a review, later dismissed

2025-01-30 20:50 UTC, Crispy-Salesforce approved these changes

2025-01-31 17:29 UTC, merged